In [1]:
import torch

In [2]:
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

In [3]:
describe(torch.Tensor(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-9.9334e+18, -4.2007e+36, -2.3128e+09],
        [-4.2008e+36, -2.9192e-20, -4.2008e+36]])


In [4]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.9239, 0.1587, 0.1822],
        [0.9935, 0.8191, 0.8784]])
타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[-0.6255, -0.9211, -0.5189],
        [-0.3373,  1.5836, -0.3106]])


In [5]:
describe(torch.zeros(2,3))

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
x = torch.ones(2,3)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [7]:
x.fill_(5)
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [8]:
x = torch.Tensor([[1,2,3],
                 [4,5,6]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [9]:
import numpy as np

np = np.random.rand(2,3)
describe(torch.from_numpy(np))

타입: torch.DoubleTensor
크기: torch.Size([2, 3])
값: 
tensor([[0.1775, 0.2344, 0.2984],
        [0.6390, 0.0502, 0.4584]], dtype=torch.float64)
