In [1]:
import torch

In [2]:
def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

In [3]:
x = torch.FloatTensor([[1,2],
                      [3,4]])
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 2.],
        [3., 4.]])


In [4]:
x = x.long()
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 2])
값: 
tensor([[1, 2],
        [3, 4]])


In [5]:
x = x.double()
describe(x)

타입: torch.DoubleTensor
크기: torch.Size([2, 2])
값: 
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)


In [6]:
x = torch.tensor([[1,2,3],
                 [4,5,6]], dtype=torch.int64)
describe(x)

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[1, 2, 3],
        [4, 5, 6]])


In [7]:
x = x.float()
describe(x)

타입: torch.FloatTensor
크기: torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])
