In [1]:
import torch

def describe(x):
    print("타입: {}".format(x.type()))
    print("크기: {}".format(x.shape))
    print("값: \n{}".format(x))

In [2]:
x = torch.arange(9).view(3,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([3, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [3]:
describe(x[:2, :3])

타입: torch.LongTensor
크기: torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [4]:
describe(x[1, 2])

타입: torch.LongTensor
크기: torch.Size([])
값: 
5


In [5]:
index = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=index))

타입: torch.LongTensor
크기: torch.Size([3, 2])
값: 
tensor([[0, 2],
        [3, 5],
        [6, 8]])


In [6]:
index = torch.LongTensor([0, 0, 1, 1])
describe(torch.index_select(x, dim=0, index=index))

타입: torch.LongTensor
크기: torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [0, 1, 2],
        [3, 4, 5],
        [3, 4, 5]])


In [7]:
x = torch.arange(9).view(3,3)
describe(x)

타입: torch.LongTensor
크기: torch.Size([3, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [8]:
describe(torch.cat([x, x], dim=0))

타입: torch.LongTensor
크기: torch.Size([6, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8],
        [0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [9]:
describe(torch.cat([x, x], dim=1))

타입: torch.LongTensor
크기: torch.Size([3, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5],
        [6, 7, 8, 6, 7, 8]])


In [10]:
describe(torch.stack([x, x]))

타입: torch.LongTensor
크기: torch.Size([2, 3, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]],

        [[0, 1, 2],
         [3, 4, 5],
         [6, 7, 8]]])
