In [1]:
from konlpy.tag import Komoran

In [2]:
import numpy as np

In [3]:
komoran = Komoran()

In [4]:
text = "오늘 날씨는 구름이 많아요."

In [5]:
# 명사만 추출
nouns = komoran.nouns(text)
print(nouns)

['오늘', '날씨', '구름']


In [6]:
# 단어 사전 구축 및 단어별 인덱스 부여
dics = {}
for word in nouns:
    if word not in dics.keys():
        dics[word] = len(dics)
print(dics)

{'오늘': 0, '날씨': 1, '구름': 2}


In [7]:
# 원-핫 인코딩
nb_classes = len(dics)
targets = list(dics.values())
one_hot_targets = np.eye(nb_classes)[targets]
print(one_hot_targets)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
